name: Generate Clash Configs

on:
  push:
    branches:
      - main
  workflow_dispatch: # اجازه اجرای دستی workflow
  schedule:
    - cron: '0 */2 * * *' # هر 2 ساعت یکبار اجرا شود (مثلاً ساعت 0، 2، 4، ...)

jobs:
  build:
    runs-on: ubuntu-latest # استفاده از سیستم عامل اوبونتو برای اجرای job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # گرفتن کپی از مخزن

      - name: Set up Python
        uses: actions/setup-python@v5 # تنظیم محیط پایتون
        with:
          python-version: '3.10' # استفاده از پایتون 3.10

      - name: Install Dependencies
        run: pip install pyyaml requests # نصب پکیج‌های مورد نیاز

      - name: Run Config Generator
        # مسیر صحیح اسکریپت پایتون شما
        # با توجه به اینکه generator.py در Clash/scripts/ قرار دارد.
        run: python Clash/scripts/generator.py
        env:
          GITHUB_REPOSITORY: ${{ github.repository }} # ارسال نام مخزن به اسکریپت

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5 # اکشن برای کامیت خودکار
        with:
          commit_message: "chore: auto-generate configs via updated format" # پیام کامیت
          # الگوهای فایل برای کامیت شدن - همه باید به داخل پوشه 'clash' اشاره کنند
          file_pattern: "clash/output/*.yaml clash/providers/*.txt clash/README.md clash/*.txt clash/*.yaml"
          commit_user_name: GitHub Actions Bot
          commit_user_email: actions@github.com
          commit_author: GitHub Actions Bot <actions@github.com>
