name: Scrape V2Ray Configs

on:
  push:
    branches:
      - main
  workflow_dispatch: 
  schedule:
    - cron: '0 */6 * * *' 

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the main script
        run: python main.py

      - name: Commit and push changes
        run: |
          git config --local user.name "NET Sentinel Bot"
          git config --local user.email "224584266+NetSentinel-Bot@users.noreply.github.com"
          git add -A .
          git diff-index --quiet HEAD || git commit -m "Automated config refresh completed at: $(TZ='Asia/Tehran' date '+%H:%M:%S')"
          git pull --rebase origin main
          git push
